name: Welcome to University of The Rio Grande Valley Student Repository - Bienvenidos al Repositorio de Estudiantes de la Universidad del Valle del Río Grande - ¡Bienvenidos!

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for sharing your issue in the University of The Rio Grande Valley Student Repository - Gracias por compartir su asunto de debate en el Repositorio de estudiantes de la Universidad del Valle del Río Grande'
        pr-message: 'Thank you for sharing your pull message in the University of The Rio Grande Valley Student Repository - Gracias por compartir su mensaje de extracción en el Repositorio de estudiantes de la Universidad del Valle del Río Grande'
